### ISSUE TITLE
[SOLVED]1.10?

### ISSUE THREAD

**Issue by lsymfr** [cnaude/PurpleIRC-forge-1.9#1]
any estimate on when it will support forge mc1.10?

**Comment by cnaude** [comment]
I didn't even know forge was available for 1.10. I'll have a look.

**Comment by cnaude** [comment]
https://h.cnaude.org/jenkins/job/PurpleIRC-forge-1.10/lastSuccessfulBuild/artifact/build/libs/PurpleIRC-1.10.2-1.0-1.jar
I haven't tested it, but it did compile cleanly.

**Comment by lsymfr** [comment]
wow dude, your the master , thanks a lot
